version: '3.4'

services:
  account.api1:
    container_name: account_api_1
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: src/Account.Api/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__AccountApiContext=Host=db;Port=5432;Database=AccountApiContext;Username=postgres;Password=mysecretpassword;
    networks:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  account.api2:
    container_name: account_api_2
    image: ${DOCKER_REGISTRY-}accountapi
    build:
        context: .
        dockerfile: src/Account.Api/Dockerfile
    depends_on:
        - db
    environment:
        - ConnectionStrings__AccountApiContext=Host=db;Port=5432;Database=AccountApiContext;Username=postgres;Password=mysecretpassword;
    networks:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  nginx:
    container_name: load_balancing
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - account.api1
      - account.api2
    ports:
      - "9999:9999"
    networks:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: AccountApiContext
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    networks:
      - nginx
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "330MB"
        
networks:
  nginx:
    driver: bridge