version: '3.4'

services:
  account.api1:
    container_name: account_api_1
    image: ${DOCKER_REGISTRY-}accountapi
    build:
      context: .
      dockerfile: src/Account.Api/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__AccountApiContext=Host=db;Port=5432;Database=AccountApiContext;Username=postgres;Password=mysecretpassword;
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 150M

  account.api2:
    container_name: account_api_2
    image: ${DOCKER_REGISTRY-}accountapi
    build:
        context: .
        dockerfile: src/Account.Api/Dockerfile
    depends_on:
        - db
    environment:
        - ConnectionStrings__AccountApiContext=Host=db;Port=5432;Database=AccountApiContext;Username=postgres;Password=mysecretpassword;
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 150M

  yarp.loadbalancer:
    container_name: yarp_loadbalancer
    image: ${DOCKER_REGISTRY-}yarploadbalancer
    build:
      context: .
      dockerfile: src/Yarp.LoadBalancer/Dockerfile
    depends_on:
        - account.api1
        - account.api2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 50M

  db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: AccountApiContext
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M